spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti5?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456
  thymeleaf:
    mode: LEGACYHTML5
    cache: false